### ISSUE TITLE
 QA_StructuralAnalysis_inconsistency_data

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/basic-structural-analysis-iiith#10]
Defect Description :
Experiment 3 has been given with two feedback sections. Instead only one feedback should be given for one experiment.

Actual Result :
Experiment 3 has been given with two feedback sections.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
Find the screenshot below.

![img11](https://cloud.githubusercontent.com/assets/11345237/19953074/25b068f2-a190-11e6-9cf5-99cb435949b0.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by BSravanthi** [comment]
Closed
