### ISSUE TITLE
QA_StructuralAnalysis_MissingContent_whileporting 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/basic-structural-analysis-iiith#5]
Defect Description :
In the Introduction section ( Target audience, courses aligned, prerequisites ) subsections are not ported to openedx. Under Introduction section these three above sections should be ported.

Actual Result :
In the Introduction section ( Target audience, courses aligned, prerequisites ) subsections are not ported to openedx.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![image](https://cloud.githubusercontent.com/assets/11345237/19951905/348c89cc-a187-11e6-8210-3fbbe894cc47.png)

**Comment by BSravanthi** [comment]
Fixed hence closing the issue.
