### ISSUE TITLE
 QA_StructuralAnalysis_Improper Alignment_in_content 

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/basic-structural-analysis-iiith#6]
Defect Description :
In the manual page of experiment 1,2 & 3 table is exceeding the page. Instead the
alignment of the table should be given proper for better view of the page.

Actual Result :
In the manual page of experiment 1,2 & 3 table is exceeding the page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
Find the screenshots of improper alignment of table for the experiment 1,2 & 3 below.

**Experiment1**
![exp1_manual](https://cloud.githubusercontent.com/assets/11345237/19952062/59ddeab2-a188-11e6-86a7-897c2036b2a4.png)
**Experiment2**
![exp2_manual](https://cloud.githubusercontent.com/assets/11345237/19952063/59e01756-a188-11e6-8d22-de284e3bffc3.png)
**Experiment3**
![exp3_manual](https://cloud.githubusercontent.com/assets/11345237/19952064/59e272bc-a188-11e6-93f4-fddcee2caf02.png)

**Comment by BSravanthi** [comment]
Fixed hence closing the issue
