### ISSUE TITLE
 QA_StructuralAnalysis_MissingContent_in quiz_while porting

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/basic-structural-analysis-iiith#7]
Defect Description :
In the quiz page of experiment 1, 3, 4 & 5 quiz questions are not ported. Instead quiz questions should be ported in the above mentioned experiments.
 
Actual Result :
In the quiz page of experiment 1, 3, 4 & 5 quiz questions are not ported.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
Find the screenshots of the quiz pages below.

![exp1_quiz](https://cloud.githubusercontent.com/assets/11345237/19952338/8a0b1b68-a18a-11e6-932b-90d1012c70a9.png)

![exp3_quiz](https://cloud.githubusercontent.com/assets/11345237/19952339/8a118944-a18a-11e6-85fa-6883b36f951a.png)

![exp4_quiz](https://cloud.githubusercontent.com/assets/11345237/19952341/8a1a6c62-a18a-11e6-8f94-7b0e47ffed86.png)

![exp5_quiz](https://cloud.githubusercontent.com/assets/11345237/19952340/8a14cfbe-a18a-11e6-81b4-9c7fce5f2fda.png)

**Comment by BSravanthi** [comment]
Fixed

**Comment by BSravanthi** [comment]
Closing the issue
