### ISSUE TITLE
 QA_StructuralAnalysis_Quiz_partially ported

### ISSUE THREAD

**Issue by sadhanareddy** [Virtual-Labs/basic-structural-analysis-iiith#9]
Defect Description :
In the quiz page of experiment 9 last question and the link given in this page is not ported. Instead the content of the page should be ported correctly inorder to not miss any content of the lab.

Actual Result :
In the quiz page of experiment 9 last question and the link given in this page is not ported.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
Find the screenshots below for comparision.

![img28](https://cloud.githubusercontent.com/assets/11345237/19952859/6619f630-a18e-11e6-9694-c516681284ce.png)

![img29](https://cloud.githubusercontent.com/assets/11345237/19952860/661cd2ce-a18e-11e6-9bf6-493f5baa6ebf.png)

**Comment by BSravanthi** [comment]
fixed

**Comment by BSravanthi** [comment]
Closed
